# Generated by Django 4.2.4 on 2023-09-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='coverletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('letter_template', models.FileField(max_length=600, upload_to='coverletter_templates/')),
            ],
        ),
        migrations.CreateModel(
            name='created_coverletters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('document', models.FileField(max_length=600, upload_to='created_coverletters/')),
            ],
        ),
        migrations.CreateModel(
            name='created_resumes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('document', models.FileField(max_length=600, upload_to='created_resumes/')),
            ],
        ),
        migrations.CreateModel(
            name='cv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('cv_file', models.FileField(max_length=600, upload_to='cv_templates/')),
            ],
        ),
        migrations.CreateModel(
            name='email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('doc_template', models.FileField(max_length=600, upload_to='email_templates/')),
            ],
        ),
        migrations.CreateModel(
            name='mergeddocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('com_doc', models.FileField(max_length=600, upload_to='merged_templates/')),
            ],
        ),
        migrations.CreateModel(
            name='resumetemplates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('doc_template', models.FileField(max_length=600, upload_to='resume_templates/')),
            ],
        ),
        migrations.CreateModel(
            name='sent_application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='GDG', max_length=100)),
                ('company_email', models.CharField(default='GDG', max_length=100)),
                ('coverletter', models.CharField(max_length=300)),
                ('resume', models.CharField(max_length=300)),
                ('mergedoc', models.CharField(max_length=300)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
