# Generated by Django 4.2.4 on 2023-09-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapplication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sent_application',
            name='subject',
            field=models.CharField(default='Test', max_length=100),
        ),
    ]
